# Generated by Django 6.0.5 on 2026-05-21 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('SHIPMENT_CREATED', 'Shipment Created'), ('TRANSPORTER_SELECTED', 'Transporter Selected'), ('SHIPMENT_ACCEPTED', 'Shipment Accepted'), ('SHIPMENT_REJECTED', 'Shipment Rejected'), ('SHIPMENT_IN_TRANSIT', 'Shipment In Transit'), ('SHIPMENT_DELIVERED', 'Shipment Delivered'), ('SHIPMENT_CANCELLED', 'Shipment Cancelled')], max_length=30)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clients.client')),
            ],
            options={
                'db_table': 'system_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
