# Generated by Django 6.0.5 on 2026-05-21 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('shipments', '0001_initial'),
        ('transporters', '0003_transporterzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemevent',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='systemevent',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='transporters.transporter'),
        ),
    ]
