# Generated by Django 6.0.5 on 2026-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='ruc',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='RUC'),
        ),
    ]
