# Generated by Django 6.0.5 on 2026-05-21 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporters', '0002_transporter_ruc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='transporters.transporter')),
            ],
            options={
                'db_table': 'transporter_zones',
                'ordering': ['district'],
                'unique_together': {('transporter', 'district')},
            },
        ),
    ]
