# Generated by Django 6.0.5 on 2026-05-21 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('shipments', '0001_initial'),
        ('transporters', '0003_transporterzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='shipments.shipment'),
        ),
        migrations.AddField(
            model_name='rating',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ratings_received', to='transporters.transporter'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='ratings_score_between_1_5'),
        ),
    ]
