# Generated by Django 6.0.5 on 2026-06-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_average_rating_and_more'),
        ('ratings', '0002_initial'),
        ('shipments', '0003_shipment_price_shipment_url_images'),
        ('transporters', '0003_transporterzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reviewer_role',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('TRANSPORTER', 'Transportista')], default='CLIENT', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shipments.shipment'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('shipment', 'reviewer_role'), name='ratings_unique_per_shipment_role'),
        ),
    ]
