# Generated by Django 6.0.5 on 2026-05-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
        ('transporters', '0003_transporterzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='scheduled_delivery_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de entrega programada'),
        ),
        migrations.AddConstraint(
            model_name='shipmentselection',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACEPTADO')), fields=('shipment',), name='uniq_one_accepted_transporter'),
        ),
    ]
