# Generated by Django 6.0.5 on 2026-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_scheduled_delivery_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio del envío'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='url_images',
            field=models.JSONField(blank=True, default=list, help_text='Array de URLs de imágenes del envío', verbose_name='URLs de imágenes (Cloudinary)'),
        ),
    ]
