# Generated by Django 6.0.5 on 2026-05-21 02:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('CLIENT', 'Cliente'), ('TRANSPORTER', 'Transportista')], max_length=20)),
                ('recipient_id', models.UUIDField()),
                ('channel', models.CharField(choices=[('SISTEMA', 'Sistema'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='SISTEMA', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.systemevent')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('recipient_type__in', ['CLIENT', 'TRANSPORTER'])), name='notifications_valid_recipient_type')],
            },
        ),
    ]
